exclude = [
  "1drv.ms",
  "canva.com",
  "epicgames.com",
  "freegamelottery.com",
  "github-profile-trophy.vercel.app",
  "hackerearth.com",
  "https://tek.io/3cHmNf8",
  "img.shields.io",
  "learn.deeplearning.ai",
  "linkedin.com",
  "medium.com",
  "mrdgh2821.github.io",
  "reddit.com",
  "thegamebakers.com",
  "trueachievements.com",
  "uber.com",
  "udemy.com",
]
