exclude = [
  '1drv.ms',
  'canva.com',
  'epicgames.com',
  'freegamelottery.com',
  'hackerearth.com',
  'img.shields.io',
  'linkedin.com',
  'medium.com',
  'mrdgh2821.github.io',
  'reddit.com',
  'thegamebakers.com',
  'trueachievements.com',
  'uber.com',
  'udemy.com',
]
